### ISSUE TITLE
Support for deeply nested/complex queries

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-knex#10]
We might draw the line here and just say this is too complex to handle. But essentially a query that won't work right now is something like this:

```js
{
   query: {
      $or: [
         { name: 'Doug' },
         { 
            age: {
               $gte: 18,
               $not: 25
            }
         }
      ]
  }
};
```

**Comment by daffl** [comment]
I think this is ok for now. This will probably be part of the schema and associations project (GraphQL whichever we decide on).

**Comment by egluhbegovic** [comment]
@daffl Hey, wanted to ask what this is referring to:
"schema and associations project (GraphQL whichever we decide on)."

**Comment by Straightline** [comment]
I know the feathers-schema will support "attaching results" across multiple tables. But I am not sure it will support "querying" across multiple tables. This means you could "give me posts and attach each user" But it will not support, "give me posts where  user.name = Dave".

@daffl Can correct me if I am wrong about that. I know that feathers-schema could support this in a similar fashion to https://daddywarbucks.github.io/feathers-fletching/hooks.html#joinquery. But I believe its main purpose (outside of validation, docs, and types) is to resolve results (attach related users to posts, for example).

@egluhbegovic You can checkout https://daddywarbucks.github.io/feathers-fletching/hooks.html#joinquery for a "service level" solution. You can also this example in the tests that demonstrates using Knex methods to accomplish this: https://github.com/feathersjs-ecosystem/feathers-knex/blob/284677e5b93e25ec47b522a5e4f69e64d52f7085/test/service-method-overrides.test.js#L32

**Comment by DaddyWarbucks** [comment]
Sorry. The above comment is actually from me. I did not realized I was logged in as one of my other accounts.
