### ISSUE TITLE
Object.assign not available in older Node versions

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-knex#13]
It looks like that is the only incompatibility with Node 0.12 so it might make sense to change that and/or use a polyfill.

**Comment by ekryski** [comment]
Do we care about supporting node 0.12? I guess we should talk about what versions make sense to support, especially since versions in Node are rolling along like God damn freight train right now.

**Comment by daffl** [comment]
True but there's still many people on older versions and since it would only be a minor change in this case we might want to consider it. In general I would say that every official plugin should support every Node version the latest Feathers release it is compatible with supports.

**Comment by ekryski** [comment]
:+1: I'm down with that.

**Comment by daffl** [comment]
It is actually pretty easy to add the Polyfill to Babel like this: https://github.com/feathersjs/feathers-configuration/commit/b21b066f74bdf158353c88b2aeb8e03d7a166148 (this repo might need to be updated to latest Babel though)
