### ISSUE TITLE
Should other adapters rely on this or Sequelize?

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-knex#14]
I just had another look at [Sequelize](http://docs.sequelizejs.com/en/latest/) and it looks a lot like our service interface and support things like `$in`, `$gt` etc out of the box already. I am wondering if the other *SQL adapters ([feathers-mysql](https://github.com/feathersjs/feathers-mysql), [feathers-pg](https://github.com/feathersjs/feathers-pg) and [feathers-sqlite](https://github.com/feathersjs/feathers-sqlite)) should use that instead?

**Comment by ekryski** [comment]
Hmmm. I dunno. This is starting to feel like the difference between `feathers-mongodb` and `feathers-mongoose`. Sequalize allows you to define models and schemas and stuff (which probably makes more sense for a relational db). I'm open to supporting both as long as it isn't too much work.

**Comment by daffl** [comment]
I think we can totally support both. The main question is what the official adapters should use. Currently I'm leaning towards Sequelize mainly because of the higher adoption and it lines up better with our service concept.

**Comment by ekryski** [comment]
ok let's get the first cut of these other db adapters out then we can revisit sequelize for the 2.0 release possibly.

**Comment by daffl** [comment]
Closing this since we'll do it ORM instead of Database specific.
