### ISSUE TITLE
Review patch and remove many for consistency

### ISSUE THREAD

**Issue by daffl** [feathersjs/feathers-knex#26]
Initially brought up in https://github.com/feathersjs/feathers-sequelize/pull/7, retrieving the records may not behave consistently and also won't work well when pagination is enabled.

**Comment by ekryski** [comment]
Hmm I saw the original issue in feathers-sequelize. Do you have know what the issue is with pagination? We have tests for it and they are passing so it should work...

**Comment by daffl** [comment]
We don't test remove and patch many with pagination enabled. Basically any method that calls another method may behave inconsistently. An example is that `patch` calls `find` to get the list of patched items but what if there are hooks on find? It should really go directly to the database.

**Comment by ekryski** [comment]
Ahhh. Ya ok that makes sense. :hankey: 

Yes, when we converted over to this new style it did feel a bit weird but it was keeping things DRY so I just shrugged and moved on. I guess we'll need to not reuse internal methods and just deal with things directly. Damn...

**Comment by daffl** [comment]
Shouldn't be too much though. Basically just pulling out the direct filtering logic from `.find` to re-use it in  `patch` and `remove`.

**Comment by ekryski** [comment]
Ya I think so too.

**Comment by daffl** [comment]
This should be fixed via #29
