### ISSUE TITLE
Support population one level deep

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-knex#3]
It's pretty reasonable, especially when using population inside of the server, to allow populating (ie. joining) directly related tables.

Let's take an example of getting all the blog posts for a user but you also want the comments.

When a `GET` request is sent to `/posts`, the unencoded query string syntax should probably be:

```js
{
  userId: 1,
  $populate: ['comments']
}
```

Which would result in a `find` on the **posts** table with a join on comments where `posts.id = comments.postId`.

Soliciting feedback, as you can also accomplish this with hooks, so maybe it should be left up to the user to implement.

**Comment by daffl** [comment]
I think we can do this now with the [populate hook](http://docs.feathersjs.com/hooks/bundled.html#populate) so I'm going to close this.

**Comment by startupthekid** [comment]
Yeah you can. I was going to write my own using mongooses `populate` function but all I ended up having to do was:

```javascript
userService.after(hooks.populate('posts', {
    service: '/posts'
}))
```

Works like a charm.
