### ISSUE TITLE
We shouldn't remove properties from original objects

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-knex#55]
Originally this came up in [the NeDB adapter](https://github.com/feathersjs/feathers-nedb/issues/29). But we should not be [calling `delete`](https://github.com/feathersjs/feathers-knex/blob/master/src/index.js#L188) on the original object. Instead we should make a copy and then call delete, or only pluck the keys that we want.

**Comment by daffl** [comment]
Updated feathers-service-tests and still passing because the data is already being cloned in https://github.com/feathersjs/feathers-knex/blob/master/src/index.js#L179
