### ISSUE TITLE
Exposing the query builder

### ISSUE THREAD

**Issue by leebenson** [feathersjs/feathers-knex#87]
I'm trying to figure out how to access the query builder object instead of the resolved promise containing row data that's returned by `.find()`.

I'm using this lib vs. my own 'raw' knex connection to map feathers' query operators, and its handling of pagination, etc. At the same time, I often need more granular access to what's returned in a typical `.find` -- left joins, mapping hasMany relationships, scoping SQL to a transaction, etc.

It'd be super handy to have a generic query method that could return the QB instead of the raw results... is there a best practice for doing that?

**Comment by daffl** [comment]
Good call. We're doing that for RethinkDB already where `createQuery(query)` returns a non-paginated query from a query. Shouldn't be too difficult to add to this one. Then it would be possible to create more complex queries in a `before` hook and set `hook.params.knex = query;`.

**Comment by leebenson** [comment]
Sounds great, thanks!

**Comment by daffl** [comment]
This is done in 2.6.0. Documentation can be found in https://docs.feathersjs.com/v/auk/databases/knexjs.html#customizing-the-query

**Comment by shadowRR** [comment]
Following on this, in order to be able to make joins, `createQuery` and `knexify` should scope queries to `this.table` so we don't end up with "ambiguous" column reference.

Ex:
In `createQuery`
```
let q = this.db().select(['*']);
// should be
let q = this.db().select([`${this.table}.*`]);
```

What do you guys think ?

**Comment by daffl** [comment]
@shadowRR Makes sense. Can you submit a PR?

**Comment by shadowRR** [comment]
Yes, no problem. After further testing, only `createQuery` should scope the current table for the select part of the query. For `knexify`, it is up to the user to scope it's "where", "or"... conditions.

**Comment by roelvan** [comment]
@shadowRR could you show me an example of how to do a join using the createQuery function? Cannot make it work. Thanks in advance.

**Comment by InstanceOfMichael** [comment]
@roelvan can you post an error message?
