### ISSUE TITLE
Datetype for mysql

### ISSUE THREAD

**Issue by sarkistlt** [feathersjs/feathers-knex#98]
When you try to pass JS date like `new Date().toString()`, or `new Date().toISOString()` to datetime field it won't you need to create new compatible with mysql date string `new Date().toISOString().slice(0, 19).replace('T', ' ')`, or you need to re-config your sql service what I don't want to do. It would be useful if this module will do it for you.

**Comment by daffl** [comment]
The database adapters do not do any automated type conversion since it can always be done in a small hook like this:

```js
function convertDate(fieldName) {
  return function(hook) {
    const prop = hook.data && hook.data[fieldName];

    if(prop) {
      hook.data[fieldName] = Date().toISOString().slice(0, 19).replace('T', ' ');
    }
    
    return Promise.resolve(hook);
  }  
}
```

Which can then be used like

```js
app.service('myservice').hooks({
  before: {
    create: [
      convertDate('birthdate')
    ]
  }
});
```

**Comment by sarkistlt** [comment]
Thanks for quick answer. I already use hook, but thought that it can be useful to do it in the adapter. 
But I got it what you are saying it makes sense.
